#!/usr/bin/env python3
"""
macOS build script for Parenta Scraper
Creates Mac app bundle and DMG installer
"""
import os
import sys
import shutil
import subprocess
from pathlib import Path

def main():
    print("🍎 Building Parenta Scraper for macOS...")
    
    # Paths
    script_dir = Path(__file__).parent
    root_dir = script_dir.parent
    dist_dir = root_dir / "dist"
    build_dir = root_dir / "build"
    
    # Clean previous builds
    print("🧹 Cleaning previous builds...")
    if dist_dir.exists():
        shutil.rmtree(dist_dir)
    if build_dir.exists():
        shutil.rmtree(build_dir)
    
    # Build with PyInstaller
    print("📦 Building app bundle with PyInstaller...")
    spec_file = script_dir / "macos.spec"
    cmd = [sys.executable, "-m", "PyInstaller", str(spec_file), "--clean"]
    
    result = subprocess.run(cmd, cwd=root_dir, capture_output=True, text=True)
    if result.returncode != 0:
        print(f"❌ PyInstaller failed:")
        print(result.stderr)
        return False
    
    print("✅ PyInstaller build completed")
    
    # Create user documentation
    print("📄 Creating user documentation...")
    create_macos_readme(dist_dir)
    create_chrome_install_guide(dist_dir)
    
    # Create DMG (if hdiutil available)
    print("💿 Creating DMG installer...")
    dmg_path = create_dmg_installer(dist_dir)
    
    if dmg_path:
        print(f"✅ macOS build complete: {dmg_path}")
    else:
        print(f"✅ macOS build complete: {dist_dir / 'ParentaScraper.app'}")
    
    print(f"📂 Build directory: {dist_dir}")
    
    return True

def create_macos_readme(dist_dir):
    """Create README for Mac users"""
    readme_content = """# Parenta Scraper for macOS

## Installation
1. Drag ParentaScraper.app to your Applications folder
2. Install Google Chrome (see Chrome-Install-Guide.txt)
3. Double-click ParentaScraper.app to run

## Important: Chrome Required
This app requires Google Chrome to be installed at:
/Applications/Google Chrome.app

If you don't have Chrome installed, the app will show you download instructions.

## Quick Start
1. Open ParentaScraper from Applications
2. Enter your Parenta login credentials
3. Click "Test (Last 20)" to try it out
4. Click "Full Scrape" to download all your photos

## What it does
- Downloads all photos and videos from your Parenta nursery account
- Saves photos to your home directory in `Nursery_Downloads_[Mode]` folder
- Creates a CSV file with all the post data

## Requirements
- macOS 10.15 (Catalina) or later
- Google Chrome installed
- Internet connection
- Valid Parenta nursery account

## Security Note
When you first run the app, macOS may show a security warning.
To allow the app:
1. Go to System Preferences → Security & Privacy
2. Click "Allow" next to the blocked app message
3. Or right-click the app and select "Open"

## Troubleshooting
- Install Chrome first: https://www.google.com/chrome/
- Check your internet connection
- Make sure your Parenta credentials are correct
- Photos are saved to: `/Users/[YourName]/Nursery_Downloads_[Mode]/`

## Support
For issues, visit: https://github.com/[your-username]/parenta-scraper/issues

Generated by Parenta Scraper build system
"""
    
    readme_path = dist_dir / "README.txt"
    readme_path.write_text(readme_content)

def create_chrome_install_guide(dist_dir):
    """Create Chrome installation guide"""
    guide_content = """# Installing Google Chrome for Parenta Scraper

## Why Chrome is Required
Parenta Scraper uses Chrome to access the Parenta website and download your photos.
Chrome must be installed separately (we cannot bundle it on Mac).

## Installation Steps

### Method 1: Direct Download
1. Visit: https://www.google.com/chrome/
2. Click "Download Chrome"
3. Open the downloaded file
4. Drag Chrome to your Applications folder
5. Done!

### Method 2: Using Homebrew (Advanced)
If you have Homebrew installed:
```
brew install --cask google-chrome
```

## Verification
After installation, you should see:
- Google Chrome.app in your Applications folder
- Path: /Applications/Google Chrome.app

## Troubleshooting
- If Chrome won't open: Right-click → Open (bypasses security warning)
- If Parenta Scraper can't find Chrome: Make sure it's in /Applications/
- Alternative: Install Chromium instead (free, open-source version)

## Alternative Browsers
If you prefer, you can install Chromium instead:
- Download from: https://www.chromium.org/
- Or with Homebrew: `brew install --cask chromium`

The app will automatically detect either Chrome or Chromium.
"""
    
    guide_path = dist_dir / "Chrome-Install-Guide.txt"
    guide_path.write_text(guide_content)

def create_dmg_installer(dist_dir):
    """Create DMG installer for easy distribution"""
    try:
        app_path = dist_dir / "ParentaScraper.app"
        dmg_path = dist_dir / "ParentaScraper-Mac.dmg"
        
        if not app_path.exists():
            print("❌ App bundle not found, skipping DMG creation")
            return None
        
        # Create DMG using hdiutil
        cmd = [
            "hdiutil", "create",
            "-srcfolder", str(app_path),
            "-volname", "Parenta Scraper",
            "-format", "UDZO",
            "-o", str(dmg_path)
        ]
        
        result = subprocess.run(cmd, capture_output=True, text=True)
        if result.returncode != 0:
            print(f"⚠️  DMG creation failed (hdiutil not available): {result.stderr}")
            return None
        
        print("✅ DMG created successfully")
        return dmg_path
        
    except Exception as e:
        print(f"⚠️  DMG creation failed: {e}")
        return None

if __name__ == "__main__":
    success = main()
    sys.exit(0 if success else 1)